# Generated by Django 5.2.6 on 2026-03-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_booking_total_days_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
